### ISSUE TITLE
results!!!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [kaldray/deezer#1]
hello there!tell me please this is for searching music from Deezer?if yes,I am begging you could you increase unlimited results?it would be great!I know deezer shows few results!please man!!!

**Comment by kaldray** [comment]
Hi , yes i will think about this feature , stay around !

**Comment by KENPOKASMMA1982** [comment]
thanks so much dude!do you think that you can increase unlimited results???
mate I mean that deezer api permit only 300 results maximum for every album and song!thats why I ask you if you can increase unlimited with some way!deezer says that has 60-70 millions songs and appear maximum 300 results!its not fair dude!!!

**Comment by kaldray** [comment]
Oh ok I didn't understand that. I thought you wanted to display all 300 results at once. But no i can't change the default rate limite

**Comment by KENPOKASMMA1982** [comment]
MY FRIEND HELLO!YOU DONT UNDERSTAND ME AGAIN!!!I MEAN IF YOU CAN WITH SOME WAY AS EXPERT INCREASE UNLIMITED RESULTS...MORE THAN 300 RESULTS

**Comment by kaldray** [comment]
No I can’t.

**Comment by KENPOKASMMA1982** [comment]
aaa what a pity!thanks man!
